name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set git global config (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - uses: actions/checkout@v1
    - name: Use Node.js v12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Lint
      run: |
        yarn install
        yarn lint
