name: Continous Integration

on: pull_request

jobs:
  build:
    name: Test pull requests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Use Node.js v12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install and test
      run: |
        npm install
        npm test
